// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package schema

import (
	"database/sql"
)

type User struct {
	ID         interface{}  `json:"id"`
	Email      string       `json:"email"`
	Provider   string       `json:"provider"`
	ProviderID string       `json:"provider_id"`
	CreatedAt  sql.NullTime `json:"created_at"`
}
